#version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  cmak:
    image: trivadis/cmak:latest # Assicurati di usare l'immagine corretta per CMK
    container_name: cmak
    ports:
      - "9000:9000"
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./path/to/your/application.conf:/cmak/conf/application.conf
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "letmein"  # Cambia questa chiave segreta come desideri
      KAFKA_BROKERS: "kafka:9092"
